### DISCUSSION TITLE
Evaluation metrics weights and normalization

### DISCUSSION THREAD

**Discussion by fohrloop** [dariogoetz/keyboard_layout_optimizer#84] [Q&A] [answered]
The evaluation metrics, for example `config/evaluation/default.yml` has a `metrics` block. This block has a list of different metrics. For example:

```yml
  # Each finger's load shall be relative to the specified weights
  finger_balance:
    enabled: true
    weight: 50.0
    normalization:
      type: fixed
      value: 1.0
    params:
      # Intended factors for finger load. Thumb values are ignored.
      intended_loads:
        [Left, Pinky]: 1.0
        [Left, Ring]: 1.6
        [Left, Middle]: 2.0
        [Left, Index]: 2.0
        [Left, Thumb]: 2.0
        [Right, Thumb]: 2.0
        [Right, Index]: 2.0
        [Right, Middle]: 2.0
        [Right, Ring]: 1.6
        [Right, Pinky]: 1.0

  # Each hand's load shall be close to 50%
  hand_disbalance:
    enabled: true
    weight: 40.0
    normalization:
      type: fixed
      value: 1.0
    params:
      null: null

  # Each keystroke incurs a cost (defined in the keyboard's layout config)
  key_costs:
    enabled: true
    weight: 20.0
    normalization:
      type: weight_found
      value: 1.0
    params:
      null: null
```

Could you explain how the final "cost" score is calculated from these? My first assumption is:

```
final_cost = weight1*metric1 + weight2*metric2 + .... weightN*metricN
```

is that correct? The second question is about the `normalization` block. It has two keys

- type: fixed | weight_found | weight_all
- value: float (seems to be 1.0 or 0.01)

How do the normalization parameters affect the final score?
