### ISSUE TITLE
Questions regarding keyboard-config: `modifiers`

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dariogoetz/keyboard_layout_optimizer#59]
1. Is there a way to simulate a Caps-lock for a layer?
Context: I'm thinking about optimizing a Georgian layout (you have seen the emails). It uses non-latin letters but has two layers that users can "caps-lock" to, where they can find latin letters ("abcdefg...").
Currently I'm not sure how to achieve optimization for caps-lock functionality. Could you help me with that?

2. The `modifiers`-option itself:
    1. It would be great to have some kind of explanation above the setting, explaining what it does, how it is determined which layers these modifiers switch to and what values can be used under `type`.
    2. `value` wants me to define which `MatrixPositions` need to be pressed down to activate that modifier, correct? It would be helpful to name that option something indicating what it does. I'm not sure what naming to suggest, however. The best idea I have is, again, `matrix_positions`, but I'm pretty sure we can think of something even more intuitive.
```yml
  modifiers:
    - Left:
        type: hold
        value: [[0,3]]
      Right:
        type: hold
        value: [[18,3]]
    - Left:
        type: hold
        value: [[0,2]]
      Right:
        type: hold
        value: [[18,2]]
    - Left:
        type: hold
        value: [[1,3]]
      Right:
        type: hold
        value: [[16,4]]
    - Left:
        type: hold
        value: [[0,3], [1,3]]
      Right:
        type: hold
        value: [[18,3], [16,4]]
    - Left:
        type: hold
        value: [[0,2], [1,3]]
      Right:
        type: hold
        value: [[18,2], [16,4]]
```
